
# Netlify configuration for SPA routing
[build]
  publish = "dist"

# Redirect all requests to index.html for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
